doctrine_migrations:
    dir_name: '%kernel.project_dir%/DoctrineMigrations'
    # namespace is arbitrary but should be different from App\DoctrineMigrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
