prooph_event_store:
    stores:
        main_store:
            event_store: Prooph\EventStore\Pdo\PostgresEventStore
            repositories:
                equipment:
                    repository_class: App\Repository\EquipmentRepository
                    aggregate_type: App\Entity\Equipment\Equipment
                    aggregate_translator: prooph_event_sourcing.aggregate_translator

services:
    Prooph\EventStore\Pdo\PostgresEventStore:
        arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\PostgresSimpleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

