version: '3.4'
services:
  db:
    image: postgres:9.6.2
    environment:
      POSTGRES_PASSWORD: savec
      POSTGRES_USER: savec
      POSTGRES_DB: savec
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    expose:
      - 5432

  adminer:
    image: hardware/adminer
    depends_on:
      - db

  php:
    image: avcsh/savec-php-xdebug
    environment:
      PHP_IDE_CONFIG: "serverName=docker-dev"
      XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
      APP_ENV: dev
      APP_SECRET: 62b197d90141c2d3b55e3cd69ad28b0
      DATABASE_URL: postgresql://savec:savec@db:5432/savec
    volumes:
      - .:/src:cached
      - ~/.composer/auth.json:/root/.composer/auth.json
    depends_on:
      - db

  nginx:
    build: docker/dev/nginx
    volumes:
      - .:/src:cached
    depends_on:
     - php

volumes:
    pgsql-data: ~
