dependencies:
  cache_directories:
    - ~/.composer/cache

version: 2
jobs:
  composer-cache:
    working_directory: /src
    docker:
      - image: avcsh/savec-php-dev
        environment:
          APP_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: savec-composer-{{ checksum "composer.lock" }}-{{ checksum "composer.json" }}

      - run:
          name: composer install
          command: |
            composer install --dev --no-interaction

      - save_cache:
          key: savec-composer-{{ checksum "composer.lock" }}-{{ checksum "composer.json" }}
          paths:
            - vendor


  code-style:
    docker:
      - image: avcsh/savec-php-dev
        environment:
          APP_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: savec-composer-{{ checksum "composer.lock" }}-{{ checksum "composer.json" }}

      - run:
          name: composer install
          command: |
            composer install --dev --no-interaction

      - run:
          name: Code style checker
          command: |
            /root/.composer/vendor/bin/ecs check \
            --config coding-standard.neon \
            src tests

  phpstan:
    docker:
      - image: avcsh/savec-php-dev
        environment:
          APP_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: savec-composer-{{ checksum "composer.lock" }}-{{ checksum "composer.json" }}
          
      - run:
          name: composer install
          command: |
            composer install --dev --no-interaction

      - run:
          name: phpstan
          command: |
            /root/.composer/vendor/bin/phpstan analyse \
            --level 7 \
            --memory-limit 1G \
            --configuration phpstan.neon \
            src tests

  database:
    docker:
      - image: avcsh/savec-php-dev
        environment:
          APP_ENV: test
          DATABASE_TEST_URL: postgresql://savec:savec@localhost:5432/savec

      - image: postgres:10.2-alpine
        environment:
          POSTGRES_PASSWORD: savec
          POSTGRES_USER: savec
          POSTGRES_DB: savec

    steps:
      - checkout
      - restore_cache:
          key: savec-composer-{{ checksum "composer.lock" }}-{{ checksum "composer.json" }}

      - run:
          name: composer install
          command: |
            composer install --dev --no-interaction

      - run:
          name: Doctrine validate mapping files
          command: |
            php bin/console doctrine:schema:validate --skip-sync

      - run:
          name: Execute migrations
          command: |
            php bin/console doctrine:database:create --if-not-exists
            php bin/console doctrine:migrations:migrate -n -vv --allow-no-migration

      - run:
          name: Doctrine validate schema sync with DB
          command: |
            php bin/console doctrine:schema:validate --skip-mapping

  phpunit:
    docker:
      - image: avcsh/savec-php-dev
        environment:
          APP_ENV: test
          DATABASE_TEST_URL: postgresql://savec:savec@localhost:5432/savec

      - image: postgres:10.2-alpine
        environment:
          POSTGRES_PASSWORD: savec
          POSTGRES_USER: savec
          POSTGRES_DB: savec

    steps:
      - checkout
      - restore_cache:
          key: savec-composer-phpunit-{{ checksum "composer.lock" }}-{{ checksum "composer.json" }}

      - run:
          name: composer install
          command: |
            composer install --dev --no-interaction

      - run:
          name: Execute migrations
          command: |
            php bin/console doctrine:database:create --if-not-exists
            php bin/console doctrine:migrations:migrate -n -vv --allow-no-migration

      - run:
          name: Run PHPUnit
          command: |
            php vendor/bin/phpunit --log-junit ~/phpunit/junit.xml

      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit

      - save_cache:
          key: savec-composer-phpunit-{{ checksum "composer.lock" }}-{{ checksum "composer.json" }}
          paths:
            - vendor

workflows:
  version: 2
  code_style_test:
    jobs:
      - composer-cache
      - code-style:
          requires:
            - composer-cache
      - phpstan:
          requires:
            - composer-cache
      - database:
          requires:
            - composer-cache
      - phpunit:
          requires:
            - code-style
            - phpstan
            - database

